config/routes.rb
Cand1992Portfolio::Application.routes.draw do
  
  resources :projects

  get "contact-us", to: "contact#new", as: :contact
  post "contact-us", to: "contact#create", as: :contact

  devise_for :users, controllers: {registrations: "user/registrations",  omniauth_callbacks: "omniauth_callbacks" }

root :to => "static_pages#home"
get "path", to: "controller#action", as: :name_of_path

get "home", to: "static_pages#home", as: :home

get "about-me", to: "static_pages#about_me", as: :about_me

end

app/models/message.rb
class Message 

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :body, :email, :name, :subject
    
  validates :body, :email, :name, :subject, presence: true
  validates :email, format: { with: Devise::email_regexp }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :pictureable, polymorphic: true
  attr_accessible :caption, :description, :image
  has_attached_file :image, 
  									:styles => { 
  									:medium => "300x300>",
  									:thumb => "100x100>" },
  									default_url: "/images/:style/missing.png"

  validates :image, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :pictures, as: :pictureable
	accepts_nested_attributes_for :pictures
  attr_accessible :description, :name, :url, :pictures_attributes
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_one :picture, as: :pictureable
  accepts_nested_attributes_for :picture
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me, :picture_attributes, :provider, :uid
  validates :first_name, :last_name, presence: true

  
  

  # attr_accessible :title, :body
  after_create :send_welcome_email

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end



def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(first_name:auth.info.first_name,
                         last_name:auth.info.last_name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def set_user
  	@user = current_user if user_signed_in?
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMailer.contact_us(@message).deliver
      redirect_to root_path, notice: "Thank you for contacting us. We will be in touch."
    else
      flash.now.alert = "Please make sure the information is correct"
      render :new
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.find_for_facebook_oauth(request.env['omniauth.auth'], current_user)
		if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id], include: [:pictures, :user])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
      format.js
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @project.pictures.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def new
		build_resource({})
		resource.build_picture
		respond_with self.resource
	end
  	def edit
    	resource.build_picture
    	super
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :set_user
  def home
  end

  def about_me
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/create.html.erb
<h1>Contact#create</h1>
<p>Find me in app/views/contact/create.html.erb</p>

app/views/contact/new.html.erb
<%= content_for :seo_title, 'Send me an email' %>
<%= content_for :description, 'This page is to send an email and contact me.' %>
<div class='page-header'>
  <h1>Contact Us!</h1>
  <%= simple_form_for @message, url: contact_path do |f| %>
    <%= f.input :email %>
    <%= f.input :name %>
    <%= f.input :subject %>
    <%= f.input :body, as: :text %>
    <div class='text-center'>
    <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Home", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav"> 
      <li><%= link_to t(:about_me), about_me_path %></li>
      <li><%= link_to 'Contact Me', contact_path %></li>
      <li><%= link_to 'Projects', projects_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li> <p class='navbar-text'> Signed in as <%= current_user.first_name.titleize %></p> </li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%=link_to "Sign Up", new_user_registration_path %></li> 
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
      <% end %>
      <li>
        <p class="navbar-text"><%= Time.now.strftime("%B %-d, %Y") %> <span class="time_span"></span></p>
      </li>

    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:seo_title) ? yield(:seo_title) + " | Chris's Portfolio" : "Chris's Portfolio" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Chris\'s portfolio is a portfolio of all the work that I, Christopher Anderson, have done' %>" >
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
  <body>
    <div id="background-img" data-imgpath="<%= asset_path('parkwaydrive.jpg') %>"></div>
    <%= render 'layouts/navigation' %>

    <div class='container'>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/email.html.erb
<html>
  <head>
    <title>*|MC:SUBJECT|*</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    
  <style type="text/css">
    body,#wrap{
      background-color:#d2efef;
      text-align:center;
    }
    #layout{
      margin:10px auto;
      text-align:left;
    }
    #topbar{
      background-color:transparent;
      padding:10px 0 20px;
      color:#666;
      font-size:11px;
      font-family:Georgia;
      font-weight:normal;
      text-align:center;
    }
    #topbar{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
    #content{
      background:#ffffff;
      line-height:1.25em;
      padding:10px 20px 30px 40px;
      vertical-align:top;
    }
    .primary-heading{
      font-size:22px;
      font-weight:normal;
      color:#7e7e7e;
      font-family:Georgia;
      line-height:150%;
      text-align:center;
    }
    p.btn{
      background:#ff8e6b;
      border:3px solid #ebebeb;
      width:auto;
      color:#fff;
      text-align:center;
      margin:25px 15%;
      font-size:40px;
      font-family:Georgia;
      padding:.7em 0;
    }
    p.note{
      font-family:Georgia;
      color:#777;
      margin:0 10%;
      font-size:16px;
      line-height:1.4em;
      text-align:center;
    }
    #footer{
      background-color:transparent;
      padding:20px;
      font-size:10px;
      color:#666;
      line-height:100%;
      font-family:Georgia;
      text-align:center;
    }
    #footer a{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
    a,a:link,a:visited{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
</style></head>
  <body style="background-color: #d2efef;text-align: center;">
    <div id="wrap" style="background-color: #d2efef;text-align: center;">
      <table id="layout" border="0" cellspacing="0" cellpadding="0" width="600" style="margin: 10px auto;text-align: left;">
        <tr>
          <td id="topbar" style="background-color: transparent;padding: 10px 0 20px;color: #ff8e6b;font-size: 11px;font-family: Georgia;font-weight: normal;text-align: center;text-decoration: underline;"><!-- *|END:IF|* --></td>
        </tr>
        <tr>
          <td>
            <h1> DevPoint Labs</h1>
          </td>
        </tr>
        <tr>
          <td id="content" style="background: #ffffff;line-height: 1.25em;padding: 10px 20px 30px 40px;vertical-align: top;">
            <%= yield %>
</td>
        </tr>
        <tr>
          <td id="page_curl">
            <img src="http://gallery.mailchimp.com/0d61bb2ec9002f0e9872b8c36/images/beauty_coupon_footer.png">
          </td>
        </tr>
        <tr>
          <td id="footer" style="background-color: transparent;padding: 20px;font-size: 10px;color: #666;line-height: 100%;font-family: Georgia;text-align: center;">
              <p>Copyright &copy; <%= Time.now.year %> DevPoint Labs All rights reserved.</p>
          </td>
        </tr>
      </table>
    </div>
    <span style="padding: 0px;"></span>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :url %>
    <%= f.simple_fields_for :pictures do |p| %>
      <%= p.input :image %>
      <%= p.input :caption %>
      <%= p.input :description %>
      <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_project_modal.html.erb
<div class="modal fade" id="project-<%=project.id %>"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="false">&times;</button>
          <h4 class="modal-title"> &nbsp;</h4>
      </div>
      <div class="modal-body">
        <div class='row'>
          <div class='col-sm-6 text-center'>
            <%= image_tag project.pictures.first.image.url(:medium), class: 'featured-image img-responsive img-thumbnail' %>
          </div>
          <div class='col-sm-6'>
            <h2><%= project.name.titleize %></h2>
            <h3>By: <%= project.user.try(:first_name) %></h3>
            <p><%= simple_format project.description %></p>
            <hr>
            
          </div>          
        </div>
        <hr>
        <div class='project-thumbnails'>
          <% project.pictures.each do |pic| %>
            <%= image_tag(pic.image.url(:thumb), class: 'img-responsive img-thumbnail', data: { url:  pic.image.url(:medium) } )%>
          <% end %>
        </div>
      </div>
      <div class="modal-footer text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class='page-header'>
  <h1> My Projects</h1>
</div>
<div class='project-info'></div>
<div class='row'>
  <% @projects.each do |project| %>
    <div class='project-tile col-xs-6 col-sm-4 col-md-3 no-gutters' >
      <%# render 'projects/project_modal', project: project %>
      <div class='project-title'>
        <h4><%= project.name.try(:titleize) %></h4>
        <p><%= project.user.try(:first_name) %></p>
        <p>
          <%= link_to "Show More >", project_path(project), remote: true %>
        </p>
      </div>
      <%= image_tag project.pictures.first.image.url(:medium), class: 'img-responsive' %>
    </div>
  <% end %>
</div>
<%= javascript_include_tag "projects" %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Url:</b>
  <%= @project.url %>
</p>

<p>
	<% if user_signed_in? && @project.picture %>
      <%= image_tag @project.picture.image.url(:medium) %>  
      <% end %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/about_me.html.erb
<%= content_for :seo_title, 'A little about myself' %>
<%= content_for :description, 'This page has some more information on myself.' %>
<h1>About me</h1>
<div>
<p>
	You can find me on github <a href="http://github.com/cand1992" target="_blank">@cand1992</a>
</p>

</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Christopher Anderson's Portfolio.</h1>
    <p>I just created this website about an hour ago. </br>Its looking pretty great so far.</p>
    <div id="wtime">
      <p>It is now <span class="time_span"></span></p>    
      <% if user_signed_in? && @user.picture %>
      <div align="center">
      <%= image_tag @user.picture.image.url(:medium) %>  
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag "home" %>